// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btjaqrwctveeffrcympz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0amFxcndjdHZlZWZmcmN5bXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODg1NTgsImV4cCI6MjA2MTA2NDU1OH0.qlmobvRAgjCqWKUJ79p7d4OYoBZCxc2exOtUUS1J2LU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);